package com.email.writer;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Service;
import org.springframework.web.reactive.function.client.WebClient;

@Service
public class EmailGeneratorService {

    private final WebClient webClient;
    private final String apiKey;

    public EmailGeneratorService(
            WebClient.Builder webClientBuilder,
            @Value("${gemini.api.url}") String baseUrl,
            @Value("${gemini.api.key}") String geminiApiKey) {

        this.apiKey = geminiApiKey;

        this.webClient = webClientBuilder
                .baseUrl(baseUrl)
                .build();
    }

    public String generateEmailReply(EmailRequest emailRequest) {

        String prompt = buildPrompt(emailRequest);

        String requestBody = String.format("""
                {
                  "contents": [
                    {
                      "parts": [
                        {
                          "text": "%s"
                        }
                      ]
                    }
                  ]
                }
                """, prompt.replace("\"", "\\\""));

        try {

            String response = webClient.post()
                    .uri(uriBuilder ->
                            uriBuilder.queryParam("key", apiKey).build())
                    .contentType(MediaType.APPLICATION_JSON)
                    .bodyValue(requestBody)
                    .retrieve()
                    .bodyToMono(String.class)
                    .block();

            return extractResponseContent(response);

        } catch (Exception e) {
            e.printStackTrace();
            return "Error calling Gemini API: " + e.getMessage();
        }
    }

    private String extractResponseContent(String response) {

        try {

            ObjectMapper mapper = new ObjectMapper();

            JsonNode rootNode = mapper.readTree(response);

            JsonNode candidates = rootNode.path("candidates");

            if (candidates.isMissingNode() || candidates.isEmpty()) {
                return "No response generated by Gemini.";
            }

            return candidates
                    .get(0)
                    .path("content")
                    .path("parts")
                    .get(0)
                    .path("text")
                    .asText();

        } catch (Exception e) {
            return "Error parsing Gemini response: " + e.getMessage();
        }
    }

    private String buildPrompt(EmailRequest emailRequest) {

        String tone = emailRequest.getTone() != null
                ? emailRequest.getTone()
                : "professional";

        return """
                You are an expert email assistant.

                Read the email below and generate an appropriate reply.

                Rules:
                - Write ONLY the email reply.
                - Do NOT generate a subject line.
                - Do NOT summarize the email.
                - Do NOT repeat the original email.
                - Keep the reply concise and professional.
                - Match the tone: %s
                - Add a suitable greeting.
                - Add a suitable closing.

                Special Rule:
                - If the email is a newsletter, promotion, event announcement,
                  marketing email, automated notification, or informational update,
                  generate a short acknowledgement reply.

                Original Email:
                %s

                Reply:
                """
                .formatted(
                        tone,
                        emailRequest.getEmailContent()
                );
    }
}